### ISSUE TITLE
Souci d'exécution de l'installer sur Windows (10)

### ISSUE THREAD

**Issue by pascalcauquil** [OB7-IRD/akado2#22]
Nous ne parvenons pas à exécuter l'installer sur nos postes Windows 10 Pro.

Java openJDK 17 x64.

Commande exécutée : java -jar akado-xxxxx-exe.jar

![Capture d’écran 2023-07-11 123420](https://github.com/OB7-IRD/akado/assets/64549487/e165f336-3884-474c-adb3-6483c161adc7)

**Comment by tchemit** [comment]
@pascalcauquil pas de capture d'écran :(

**Comment by tchemit** [comment]
@pascalcauquil je n'ai rien changé dans l'installeur à ce sujet, je vois mal quoi faire

**Comment by tchemit** [comment]
peut-être essayer avec un jdk oracle ?

**Comment by pascalcauquil** [comment]
on va essayer

**Comment by pascalcauquil** [comment]
Peut-être qu'en le compilant pour Java 11 les exigences de lib sont moins importantes.

**Comment by pascalcauquil** [comment]
Même souci avec le Java 17 x64 officiel d'Oracle :

![Capture](https://github.com/OB7-IRD/akado/assets/64549487/9af6fa5c-fde0-498c-9932-719cdb3c4cb8)

**Comment by pascalcauquil** [comment]
Il faudrait compiler pour Java 11, je crois avoir déjà vu ce problème.

**Comment by pascalcauquil** [comment]
https://stackoverflow.com/questions/74964285/java-8-to-17-upgrade-issue-java-lang-illegalaccesserror

**Comment by tchemit** [comment]
J'ai tout simplement supprimé le Look-and-feel spécifique pour windows. Ça devrait alors bien fonctionner

**Comment by pascalcauquil** [comment]
Pourras-tu nous faire une release ou une snapshot, que l'on soit fixés ?

**Comment by tchemit** [comment]
@pascalcauquil oui je vais faire release

**Comment by tchemit** [comment]
la jdk minimum requise est java 11, mais tu devrais pouvoir l'installer avec java > 11

**Comment by tchemit** [comment]
la release a été délivrée

**Comment by pascalcauquil** [comment]
ça corrige le problème, merci
