### ISSUE TITLE
Faire indiquer le temps de pêche

### ISSUE THREAD

**Issue by pascalcauquil** [OB7-IRD/akado2#23]
Akado alerte sur le temps de mer, et il indique la somme qu'il obtient en sommant les temps de mer des toutes les routes :
![image](https://github.com/OB7-IRD/akado/assets/64549487/14e1d2a0-fe80-42dc-b9ce-3aad5c450bda)

Il faudrait qu'il affiche, de la même manière, la somme calculée des temps de pêche.

**Comment by tchemit** [comment]
@pascalcauquil est-il possible, plutôt que de me fournir des impression-écran de juste copier le texte dans le corp du ticket, une image ne m'aide pas alors que le texte je peux faire des copier-coller depuis ;) merci
