### ISSUE TITLE
ZEE déduite

### ISSUE THREAD

**Issue by pascalcauquil** [OB7-IRD/akado2#24]
Sur les activités du 19 au 25/06, le bateau est à Port Gentil (port du Gabon). La position renseignée est telle que le bateau est vu comme légèrement à terre. Donc Hord de toute ZEE :

<img width="1290" alt="image" src="https://github.com/OB7-IRD/akado/assets/64549487/8e20ffc5-e53b-4e3c-8232-2840a6d9cafb">
Pourrait-on remplacer le "-" par "hors zone" ?

**Comment by tchemit** [comment]
@pascalcauquil oui c'est possible, cependant, je ne vais pas pouvoir accéder à toutes tes demandes de perfection; j'ai déjà largement amélioré les messages. Je te demande donc de ne pas trop me rajouter de tickets, sinon en gros il va falloir que je retravaille tous les messages et cela n'est pas possible pour moi. Pour information, compares avec les messages du pilote avdth et tu verras que là c'est clairement des fois incompréhensibles.
Merci d'en tenir compte.

**Comment by tchemit** [comment]
@pascalcauquil si tu peux aussi renseigner les méta-données du ticket, ça m'évite de le faire...

**Comment by tchemit** [comment]
@pascalcauquil il m'est difficile de traduire cela, la traduction est faite au dernier moment bien après avoir crée le résultat. Cela semble compliqué en l'état...

**Comment by tchemit** [comment]
j'ai réussi à le faire :) mais cela est au détriment des performances, à savoir qu'à chaque message à traduire tout un tas d'objet est crée pour récupérer le fichier de traduction...
