### ISSUE TITLE
Revoir le message du controle Anapo sur les listes d'activités 

### ISSUE THREAD

**Issue by tchemit** [OB7-IRD/akado2#6]
# Existant

Dans avdth, nous avons ce message : 

```
E1428> Activité[427 30/06/2023 30/06/2023 0] Il y a des positions VMS pour le 2022-01-21T00:01:00.372Z mais aucune activité.
```

À noter que la date de débarquement et celle de l'activité est celle du jour courant.

# Nouveau message pour ObServe (repris sur l'ancien contrôle)

```
E1428> Activité[427 null 21/01/2022 ??:?? 0] Il y a des positions VMS pour le 2022-01-21T00:01:00.201Z mais aucune activité.
```

La date d'activité est en fait celle de la position VMS en cours de test.

Ici pas de date de débarquement, puisqu'on ne la connaît pas.

# Proposition 

Puisque que nous n'avons ni date de débarquement, ni celle de l'activité et uniquement la position VMS (qui nous donne l'horodatage et celle-ci ainsi que le navire ciblé), je propose qu'on n'affiche plus du tout cette activité fictive.

```
E1428> Navire [427 - CORONA DEL MAR]  Il y a des positions VMS pour le 2022-01-21T00:01:00.201Z mais aucune activité.
```

**Comment by tchemit** [comment]
@pascalcauquil tu valides ?

**Comment by pascalcauquil** [comment]
@tchemit Cela me parait raisonnable. Ceci dit je ne comprends pas pourquoi la date de débarquement n'est pas disponible dans ce cas : certes il n'y a pas d'activité, mais il me semble qu'on est bien en train de traiter une marée, donc on devrait avoir la date de débarquement. Ou bien quelque chose m'échappe encore.

**Comment by tchemit** [comment]
Le contrôle sur la liste des activités prend toutes les activités disponibles, mais à ce moment, on a plus la route, ni la marée...

**Comment by tchemit** [comment]
mais surtout c'est qu'on n'a pas d'activité de disponible pour la position vms, donc ... pas de date de débarquement non plus

**Comment by pascalcauquil** [comment]
Ok je vois, donc allons pour ta solution
