### ISSUE TITLE
Revue des espèces utilisées pour le calcul du Raising Factor

### ISSUE THREAD

**Issue by tchemit** [OB7-IRD/akado2#7]
# Contexte

Dans le contrôle AVDTH on se basait sur les codes d'espèces.

On préfère utiliser dans ObServe les topiaId.

Dans le calcul du raising factor, on distingue deux listes d'espèces (une pour la france, une pour l'espagne)

# Mapping français

```java
private static final String[] FRENCH_TARGET_SPECIES = new String[]{"1", "2", "3", "4", "9", "11", "42"};
```

a été remplacé par

```java
private static boolean isFrenchTargetSpecies(Species species) {
        return species.isYFT() // avdth code 1
                || species.isSKJ() // avdth code 2
                || species.isBET() // avdth code 3
                || species.isALB() // avdth code 4
                || species.isTUN() // avdth code 9
                || species.isLOT() // avdth code 11
                // FIXME We do not know avdth code 42 ...|| species.is???() // avdth code 42
                ;
    }
```

Le code 42 n'existe pas dans AVDTH et on ne sait pas quoi en faire...

# Mapping espagnol

```java
 private static final String[] SPAIN_TARGET_SPECIES = new String[]{"1", "2", "3", "4", "5", "6", "9", "11", "12", "42", "43"};
```

a été remplacé par

```java
private static boolean isSpainTargetSpecies(Species species) {
        return species.isYFT() // avdth code 1
                || species.isSKJ() // avdth code 2
                || species.isBET() // avdth code 3
                || species.isALB() // avdth code 4
                || species.isALB() // avdth code 5
                || species.isALB() // avdth code 6
                || species.isTUN() // avdth code 9
                || species.isLOT() // avdth code 11
                || species.isBLF() // avdth code 12
                // FIXME We do not know avdth code 42 ...|| species.is???() // avdth code 42
                || species.isRAV() // avdth code 43 FIXME Make sure this exists, did not find it in IRD referential
                ;
    }
```

Idem pour le code 42 mais aussi le 43 (dans AVDTH c'est du **RAV**). Je le trouve dans une de mes bases mais pas sur un référentiel de l'IRD. Il faut voir quoi faire.

**Comment by pascalcauquil** [comment]
Oui c'est normal ce RAV n'est pas un code standard (ne fait pas partie du référentiel ASFIS). Je te dirai une fois devant l'ordi quel est le code standard qui le remplace.

**Comment by tchemit** [comment]
@pascalcauquil sauf erreur de ma part, dans la migration AVDTH → ObServe, on renvoie les codes 43 et 843 vers l'espèce ``RAV*``

Cette espèce existe bien dans ObServe.

**Comment by pascalcauquil** [comment]
42 on le laisse tomber, puisqu'il n'existe pas dans AVDTH.

43 : Pour résumer, 43 (843 ?) n'est utilisé que pour l'estimation du RF que sur les données espagnoles. La question concerne donc le calcul espagnol seulement. Réponse en 2 étapes :

1. Tu as raison, bien que le code RAV ne soit pas standard, on avait jugé trop risqué (je l'avais oublié) de mapper vers d'autres codes plus standards car c'est un code bâtard qui regroupe plusieurs espèces de thons mineurs, et surtout les français et les espagnols n'englobent pas forcément le même jeu d'espèces sous ce code. On avait donc décidé de garder un RAV* (le * signifiant "non standard"). C'était ici : https://gitlab.com/ultreiaio/ird-observe/-/issues/2421

Donc oui, 43 (RAV AVDTH capturé) et 843 (RAV AVDTH rejeté) sont à remplacer par RAV* dans la liste des espèces à incorporer au calcul du RF espagnol, pour le calcul fait depuis ObServe. Ce sera utile pour les données migrées d'AVDTH, qui sont utilisatrices de RAV* suite à leur migration.

2. Ceci dit, l'utilisation de 43 et 843, c'était dans AVDTH. Dans ObServe, l'utilisation de RAV* sera découragée. Lorsque les saisies auront été faites par ObServe, il pourra y avoir du RAV* si les espagnols s'obstinent, mais il devrait être remplacé au profit de : 
  * LTA
  * KAW
  * FRZ
  * BLT
  * FRI

Il faut donc ajouter ces espèces à la liste du calcul du RF espagnol. Ce sera utile pour le calcul du RF fait depuis des données acquises directement sous ObServe.

**Comment by tchemit** [comment]
@pascalcauquil bien noté, je supprime le code 42 de mon commentaire alors, un de moins! cool

**Comment by pascalcauquil** [comment]
Liste complétée ci-dessus
